### ISSUE TITLE
ES Version, Home: DOB Month has 1 month offset

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#104]
1. switch to ES
2. enter e.g. 24 08 1980 Algeria female
3. result: http://population.io/#/1980/09/24/female/Algeria/home (note the '09' in URL)

**Comment by LukaszCaputa** [comment]
i cannot reproduce the error on firefox osx 10
i get following url for data from point 2
http://population.io/#/1980/08/24/female/Algeria/summary

**Comment by b-g** [comment]
Hi @LukaszCaputa,

odd ... here is a screencast how to reproduce it: http://dl.dropbox.com/u/2700930/ES_Month_Offset_Bug.mov

Best,
B

**Comment by LukaszCaputa** [comment]
now i can reproduce it :)
it's a very strange bug - not even sure what could cause such a behaviour 
seems people born on august are discriminated ...

**Comment by LukaszCaputa** [comment]
i found where the bug is - but no idea how to fix it cos problem seems to be in Moment.js library

Code below (part of function goGoGadget) returns for English version: August 08
but for Spanish : august 09 

console.log("goGoGadget month1: "+ProfileService.birthday.month);

                  var year = moment().year(ProfileService.birthday.year).format('YYYY'),
                    month = moment().month(ProfileService.birthday.month).format('MM'),
                    day = moment().date(ProfileService.birthday.day).format('DD');
console.log("goGoGadget month2: "+month);

i tried to upgrade moment.js to newest version that is 2.10.6 but it didn't help at all.

I even swapped ES.json with EN.json so by default we load spanish translations and ... problem was still there. How come, no idea. 

@b-g any propositions on how to fix that issue ? Cos i'm clueless

**Comment by b-g** [comment]
Tricky! Could it be a glitsch around the classic Javascript month numbering issue (Jan = 0, Dez = 11, http://stackoverflow.com/a/12254344)? Bascially that the month numbering of ProfileService.birthday.month and moment.js is not the same?

**Comment by LukaszCaputa** [comment]
i don't think so - because for all other month - english and spanish - function works just fine

i can implement an ugly fix ( if month = augusto and result not 8 then result = 8)
what do you think about it ?

**Comment by b-g** [comment]
thanks for the hack! :)
