### ISSUE TITLE
Home: change distribution of countries in the babies animation to real world

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#83]
At the moment the countries in the baby animation are equally distributed by a normal random function. As this doesn't reflect reality, we would like to change the distribution of countries to the correct ones, see:
https://github.com/worldpopulation/population.io/blob/master/data/births_distribution_in_the_world_2015.csv

**Comment by kcsamir** [comment]
Hi, due to rounding to two decimals some countries with smaller population size has .00 values and will never appear. Maybe not a big issue - should we go for three decimals? Or may be you have already thought of this, in that case, please ignore.

**Comment by b-g** [comment]
No haven't thought about this :) Let's go then for 3 decimals ... please update and commit the CSV file. Many thanks.

**Comment by kcsamir** [comment]
Just created a file. I hope it is fine. Please check
https://github.com/worldpopulation/population.io/blob/master/data/Births_distribution_in_the_world_2015.txt

**Comment by kcsamir** [comment]
I will send the csv file in attachment.. could not figure out how to upload it :(

**Comment by kcsamir** [comment]
three decimals, file attached!

On Wed, Mar 11, 2015 at 1:27 PM, Benedikt Groß <notifications@github.com>
wrote:

> No haven't thought about this :) Let's go then for 3 decimals ... please
> update and commit the CSV file. Many thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/worldpopulation/population.io/issues/83#issuecomment-78253396>
> .
>



-- 
Samir K.C., Ph.D.
Project Leader, Modelling Human Capital
World Population Program
International Institute for Applied Systems Analysis

**Comment by nikolaskaramuca** [comment]
Babies in animation are now selected randomly but each country's probabilty (as defined in Births_distribution_in_the_world_2015.txt) is taken into account. Also, greetings were not in sync with the countries since there was a separate random function called to select greetings string after a country was already selected. This is also corrected but there are some discrepancies still left as some countries are defined in the application but are missing in birth distribution file and vice versa.

Countries listed in birth distribution file but not defined in the application:

1.	FYR Macedonia
2.	Channel Islands
3.	Macao SAR China
4.	Curacao
5.	Timor-Leste
6.	South Sudan
7.	Western Sahara
8.	Hong Kong SAR-China
9.	India
10.	Japan
11.	Dem Peoples Rep of Korea
12.	Rep of Korea
13.	Greece
14.	Cyprus
15.	West Bank and Gaza


Countries defined in applicataion but missing in birth distribution file:

1.	Andorra
2.	Anguilla
3.	Netherlands Antilles
4.	Asia/Pacific Region
5.	Antarctica
6.	American Samoa
7.	Aland Islands
8.	Bermuda
9.	Bouvet Island
10.	Cook Islands
11. 	Dominica
12. 	Europe
13.	Falkland Islands (Malvinas)
14.	Faroe Islands
15.	Great Britain
16.	Guernsey
17.	Gibraltar
18.	Greenland
19.	Isle of Man
20.	British Indian Ocean Territory
21.	Jersey
22.	Saint Kitts and Nevis
23.	Cayman Islands
24.	Liechtenstein
25.	Monaco
26.	Marshall Islands
27.	Northern Mariana Islands
28.	Montserrat
29.	Norfolk Island
30.	Nauru
31.	Niue
32.	Saint Pierre and Miquelon
33.	Palestinian Territory
34.	Palau
35.	San Marino
36.	Turks and Caicos Islands
37.	Tokelau
38.	Turkmenistan
39.	Tuvalu
40.	United States Minor Outlying Islands
41.	Holy See (Vatican City State)
42.	Virgin Islands  British
43.	Wallis and Futuna

**Comment by b-g** [comment]
Hi @nikolaskaramuca, Many thanks for this! Can you bring it in sync by simply using the countries defined in the birth distribution table as the "master countries" list? Especially the big countries in terms of population like India are important ... Best, B
PS. Where can I find the your improvements? Maybe now PR on the [develop](https://github.com/worldpopulation/population.io/tree/develop) branch?

**Comment by nikolaskaramuca** [comment]
Countries defined in application are updated as you suggested, using birth distribution table as the master list.
